image: mobiledevops/android-sdk-image:36.1.0

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test

unit-tests:
  stage: test
  script:
    - ./gradlew :app:testDebugUnitTest --no-daemon --stacktrace
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  artifacts:
    when: always
    reports:
      junit: app/build/test-results/testDebugUnitTest/*.xml
    paths:
      - app/build/reports/tests/testDebugUnitTest/
    expire_in: 1 week
  timeout: 30m