name: Renovate

on:
  schedule:
    - cron: '0 0 * * 6'  # Saturday 00:00 UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: info
